# Form implementation generated from reading ui file 'ephemDialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(320, 151)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ephemProgressBar = QtWidgets.QProgressBar(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ephemProgressBar.sizePolicy().hasHeightForWidth())
        self.ephemProgressBar.setSizePolicy(sizePolicy)
        self.ephemProgressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.ephemProgressBar.setProperty("value", 0)
        self.ephemProgressBar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.ephemProgressBar.setObjectName("ephemProgressBar")
        self.verticalLayout.addWidget(self.ephemProgressBar)
        self.ephemAbortButtonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ephemAbortButtonBox.sizePolicy().hasHeightForWidth())
        self.ephemAbortButtonBox.setSizePolicy(sizePolicy)
        self.ephemAbortButtonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.ephemAbortButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Abort)
        self.ephemAbortButtonBox.setCenterButtons(True)
        self.ephemAbortButtonBox.setObjectName("ephemAbortButtonBox")
        self.verticalLayout.addWidget(self.ephemAbortButtonBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Fetching Ephemeris"))
